account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("/login", views.login, name="login"),
    path("/logout", views.logout, name="logout"),
    path("/auth", views.auth, name="auth"),
    path("/delete", views.delete, name="delete"),
    path("/unsubscribe", views.unsubscribe, name="unsubscribe"),
    path("/sample_email_digest", views.sample_email_digest, name="sample_email_digest"),
    path("", views.account, name="account"),
]

activity/urls.py
from django.urls import path

from . import views

app_name = "activity"

urlpatterns = [
    path("/search", views.search, name="search"),
    path("/delete", views.delete, name="delete"),
    path("/refresh", views.refresh, name="refresh"),
    path("", views.activity, name="activity"),
]

project/urls.py
from coltrane.sitemaps import ContentSitemap
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from fbv.views import favicon_emoji, favicon_file

from account import urls as account_urls
from activity import urls as activity_urls
from www import urls as www_urls

ContentSitemap.protocol = "https"

sitemaps = {
    "content": ContentSitemap,
}

urlpatterns = [
    path(f"{settings.ADMIN_SITE_BASE_URL}/", admin.site.urls),
    path("unicorn/", include("django_unicorn.urls")),
    path("favicon.ico", favicon_emoji, {"emoji": "🐘"}),
    path(r"apple-touch-icon.png", favicon_emoji, {"emoji": "🐘"}),
    path(r"apple-touch-icon-precomposed.png", favicon_emoji, {"emoji": "🐘"}),
    path("robots.txt", favicon_file, {"file_path": "www/robots.txt"}),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("account", include(account_urls, namespace="account")),
    path("activity", include(activity_urls, namespace="activity")),
    path("", include(www_urls, namespace="www")),
    path("", include("coltrane.urls")),
]

www/urls.py
from django.urls import path

from . import views

app_name = "www"

urlpatterns = [
    path("plus/auth", views.plus_auth, name="plus_auth"),
    path("plus/oauth", views.plus_oauth, name="plus_oauth"),
    path("plus", views.plus, name="plus"),
    path("", views.index, name="index"),
]

www/views.py
from uuid import uuid4

import httpx
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.sites.shortcuts import get_current_site
from django.core.cache import cache
from django.http import HttpRequest
from django.shortcuts import redirect
from fbv.decorators import render_html

from account.models import GitHubAccount
from unicorn.components.sponsor import check_sponsorship


@render_html("www/index.html")
def index(request):
    return {}


def _get_redirect_uri(request):
    site = get_current_site(request)
    redirect_uri = f"https://{site.domain}/plus/oauth"

    return redirect_uri


@render_html("www/plus.html")
def plus(request):
    return {}


@login_required
def plus_auth(request):
    client_id = settings.GITHUB_CLIENT_ID
    redirect_uri = _get_redirect_uri(request)
    state = str(uuid4())

    cache.set(f"github:oauth:{state}", request.user.id, timeout=500)

    url = f"https://github.com/login/oauth/authorize?client_id={client_id}&redirect_uri={redirect_uri}&scope=read:user&state={state}"

    return redirect(url)


def _get_access_token(request: HttpRequest) -> str:
    redirect_uri = _get_redirect_uri(request)

    code = request.GET.get("code")
    assert code, "code is required"

    res = httpx.post(
        "https://github.com/login/oauth/access_token",
        data={
            "client_id": settings.GITHUB_CLIENT_ID,
            "client_secret": settings.GITHUB_CLIENT_SECRET,
            "code": code,
            "redirect_uri": redirect_uri,
        },
        headers={"Accept": "application/json"},
    )

    res.raise_for_status()
    data = res.json()

    access_token = data["access_token"]

    return access_token


def _get_username(access_token: str) -> str:
    res = httpx.get(
        "https://api.github.com/user",
        headers={
            "Authorization": f"Bearer {access_token}",
            "Accept": "application/vnd.github+json",
        },
    )

    res.raise_for_status()
    user_json = res.json()
    github_username = user_json["login"]

    return github_username


@login_required
def plus_oauth(request):
    state = request.GET.get("state")
    assert state, "state is required"

    user_id = cache.get(f"github:oauth:{state}")

    if not user_id:
        raise Exception("Invalid state")

    assert request.user.id == user_id, "Oauth user not same as logged in user"

    access_token = _get_access_token(request)

    github_username = _get_username(access_token)

    github_account = GitHubAccount(
        account=request.user.account,
        access_token=access_token,
        username=github_username,
    )
    github_account.save()

    if check_sponsorship(github_username):
        messages.success(request, "Thank you for sponsoring me!")

        return redirect("/account")

    return redirect("/plus#sign-up")

www/templates/www/base.html
{% load cache compress git mastodon settings_tags static unicorn %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta chartset="utf-8" />
    <meta name="description" content="Generate an algorithmic summary for Mastodon timelines">
    <meta name="keywords" content="Mastodon, Fediverse, Algorithm, Summary, Social Media">
    <meta name="author" content="John Doe">
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <link rel="canonical" href="https://fediview.com/{{ request.get_full_path }}" />

    <title>fediview - {% if title %}{{ title }}{% else %}The algorithmic timeline for Mastodon{% endif %}</title>

    {% compress css %}
    <link rel="stylesheet" href="{% static 'css/marx.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/utils.css' %}">
    <link rel="stylesheet" href="{% static 'css/base.css' %}">
    <link rel="stylesheet" href="{% static 'css/stepper.css' %}">
    <link rel="stylesheet" href="{% static 'css/tooltip.css' %}">
    {% endcompress %}

    {% if not debug %}
    {% analytics_html %}
    {% endif %}

    {% block css %}
    {% endblock css %}

    <link rel="stylesheet" type="text/css" href="{% static 'toastify/1.12.0/toastify.min.css' %}">
    <script type="text/javascript" src="{% static 'toastify/1.12.0/toastify.js' %}"></script>

    {% compress js %}
    <script src="{% static 'js/base.js' %}"></script>
    {% endcompress %}

    {% block js %}
    {% endblock js %}
</head>

<body class="{{ body_class }}">
    {% csrf_token %}
    <nav>
        <ul>
            <!-- left nav -->
            <li class="brand">
                <span class="icon">🔍</span>
                <a href="/" class="plausible-event-name=nav-home">
                    fediview
                </a>
            </li>
            {% if user.is_authenticated and user.account.profile.has_plus %}
            <li>
                <a href="{% url 'activity:activity' %}" class="plausible-event-name=nav-activity-activity">
                    Activity
                </a>
            </li>
            <li>
                <a href="{% url 'activity:search' %}" class="plausible-event-name=nav-activity-search">
                    Search
                </a>
            </li>
            {% else %}
            <li>
                <a href="{% url 'www:plus' %}" class="plausible-event-name=nav-plus">
                    Plus
                </a> ✨
            </li>
            {% endif %}

            <!-- right nav -->
            <li class="auth">
                {% if request.user.is_authenticated %}
                <form action="{% url 'account:logout' %}" method="POST" style="text-align: right;">
                    {% csrf_token %}
                    {% if request.user.account.profile %}
                    <span style="padding-right: .5em;" class="username">
                        <a href="{% url 'account:account' %}" class="plausible-event-name=nav-username">
                            {{ request.user.username|username_no_server }}
                        </a>
                    </span>
                    {% endif %}
                    <button class="plausible-event-name=nav-logout">Logout</button>
                </form>
                {% else %}
                {% csrf_token %}
                <div style="text-align: right;">
                    <a href="{% url 'account:login' %}" class="plausible-event-name=nav-login">
                        <button>Login with Mastodon</button>
                    </a>
                </div>
                {% endif %}
            </li>
        </ul>
    </nav>

    <main>
        <header style="border-bottom: dashed 1px; margin-bottom: 2em; padding: .6em;">
            <div style="display: flex;">
                <div style="flex-grow: 1; padding-right: 1em;">
                    <h1 class="tagline"
                        style="font-size: var(--font-size-h3); text-align: center; margin: var(--md-pad) 0 var(--xs-pad);">
                        <span>
                            {% block header %}
                            {{ header }}
                            {% endblock header %}
                        </span>
                    </h1>
                </div>
            </div>
        </header>

        {% block content %}
        {{ content }}
        {% endblock content %}

        <footer>
            {% block digitalocean %}
            {% if not request.user.is_authenticated or not request.user.account.profile.has_plus %}
            <div style="padding-top: 1.5em; padding-bottom: 1em;">
                <a
                    href="https://www.digitalocean.com/?refcode=617d629f56c0&utm_campaign=Referral_Invite&utm_medium=Referral_Program&utm_source=badge"><img
                        src="https://web-platforms.sfo2.digitaloceanspaces.com/WWW/Badge%201.svg"
                        alt="DigitalOcean Referral Badge" />
                </a>
            </div>
            {% endif %}
            {% endblock digitalocean %}

            <div id="footer-links">
                <div class="links">
                    <p class="footer-header">Articles</p>
                    <ul>
                        <li>
                            <a href="{% url 'coltrane:content' 'faq' %}"
                                class="{% if request.path == '/faq' %}active{% endif %} plausible-event-name=footer-faq">
                                FAQ
                            </a>
                        </li>
                        <li>
                            <a href="{% url 'coltrane:content' 'what-is-mastodon' %}"
                                class="plausible-event-name=footer-what-is-mastodon">What is Mastodon?</a>
                        </li>
                        <li>
                            <a href="{% url 'coltrane:content' 'best-tools-for-mastodon' %}"
                                class="plausible-event-name=footer-best-tools-for-mastodon">Tools for
                                Mastodon</a>
                        </li>
                    </ul>
                </div>

                <div class="links">
                    <p class="footer-header">Code</p>
                    <ul>
                        <li>
                            <a href="{% url 'coltrane:content' 'changelog' %}"
                                class="{% if request.path == '/changelog' %}active{% endif %} plausible-event-name=footer-changelog">
                                Changelog
                            </a>
                        </li>
                        <li>
                            <a href="https://github.com/adamghill/fediview">fediview</a> by <a
                                href="https://indieweb.social/@adamghill">@adamghill</a>
                        </li>
                        <li>
                            <a href="https://github.com/hodgesmr/mastodon_digest">Digest script</a>
                            by <a href="https://mastodon.social/@MattHodges">@MattHodges</a>
                        </li>
                        <li>
                            <a href="https://github.com/mauforonda/mastodon_digest">Digest script fork</a>
                            by <a href="https://hachyderm.io/@mauforonda">@mauforonda</a>
                        </li>
                        <li>
                            <a href="https://github.com/mauforonda/mastodon_links">Links script</a>
                            by <a href="https://hachyderm.io/@mauforonda">@mauforonda</a>
                        </li>
                    </ul>
                </div>

                <div class="links">
                    <p class="footer-header">Built with</p>
                    <ul>
                        <li>
                            <a href="https://www.django-unicorn.com">django-unicorn</a>
                        </li>
                        <li>
                            <a href="https://coltrane.readthedocs.io">coltrane</a>
                        </li>
                        <li>
                            <a href="https://github.com/halcy/Mastodon.py">mastodon.py</a>
                        </li>
                        <li>
                            <a href="https://docs.pydantic.dev/">pydantic</a>
                        </li>
                        <li>
                            <a href="https://www.djangoproject.com">Django</a>
                        </li>
                        <li>
                            <a href="https://mblode.github.io/marx/">Marx CSS</a>
                        </li>
                        <li>
                            <a href="https://apvarun.github.io/toastify-js/">Toastify</a>
                        </li>
                        <li>
                            <a href="https://m.do.co/c/617d629f56c0">DigitalOcean</a>
                        </li>
                    </ul>
                </div>

                <div class="links">
                    <p class="footer-header">Other sites</p>
                    <ul>
                        <li>
                            <a href="https://indieweb.social/@adamghill/">@adamghill</a>
                        </li>
                        <li>
                            <a href="https://devmarks.io">devmarks.io</a>
                        </li>
                        <li>
                            <a href="https://adamghill.com">adamghill.com</a>
                        </li>
                        <li>
                            <a href="https://adamghill.com/python-utils">python-utils</a>
                        </li>
                        <li>
                            <a href="https://unsuckjs.com">unsuckjs</a>
                        </li>
                        <li>
                            <a href="https://alldjango.com">alldjango.com</a>
                        </li>

                    </ul>
                </div>
            </div>

            {% git_version as git_version %}

            {% if git_version %}
            <p>
                Version:
                <a href="https://github.com/adamghill/fediview/commit/{{ git_version }}">
                    {{ git_version }}
                </a>
            </p>
            {% endif %}
        </footer>
    </main>

    <script>
        function notify(message, type) {
            if (!type) {
                type = 'is-success'
            }

            Toastify({
                text: message,
                duration: 3000,
                position: 'center',
                stopOnFocus: true,
            }).showToast();
        }
    </script>

    {% if messages %}
    {% for message in messages %}
    <script>
        var tag = '{{ message.tags }}';
        var type = 'is-success';

        if (tag == "error") {
            type = 'is-danger';
        } else if (tag == "warning") {
            type = 'is-warning';
        }

        document.addEventListener('DOMContentLoaded', () => {
            notify('{{ message }}', type);
        });
    </script>
    {% endfor %}
    {% endif %}
</body>

</html>

www/templates/www/index.html
{% extends 'www/base.html' %}
{% load cache compress static unicorn %}


{% block css %}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/glightbox/dist/css/glightbox.min.css" />
{% endblock css %}

{% block js %}
{% unicorn_scripts %}

<script src="https://cdn.jsdelivr.net/gh/mcstudios/glightbox/dist/js/glightbox.min.js"></script>

{% compress js %}
<script>
    function updateHours() {
        var hours = document.getElementById("hours");
        var hoursValue = document.getElementById("hoursValue");

        if (hours) { // Update the current slider value (each time you drag the slider handle)
            hours.oninput = function () {
                hoursValue.innerHTML = this.value;
            }
        }
    }

    function saveLocal() {
        const saveInputTextboxIds = ['url', 'token', ];
        const saveInputCheckboxId = 'saveInputs';
        const manualAuthorizationDetailsId = 'manual-authorization';

        // Load the url and token from localstorage
        var loadInputs = function ($saveInput) {
            const saveInput = localStorage.getItem(saveInputCheckboxId);
            var isChecked = false;

            if (saveInput && saveInput === "true") {
                isChecked = true;
            }

            $saveInput.checked = isChecked;

            if (isChecked) {
                saveInputTextboxIds.forEach(function (id) {
                    const val = localStorage.getItem(id);

                    if (val) {
                        document.getElementById(id).value = val;

                        // Make sure that unicorn "sees" the change to the text input
                        Unicorn.trigger("timeline", id);
                    }
                });

                let $manualAuthorizationDetails = document.getElementById(manualAuthorizationDetailsId);

                if ($manualAuthorizationDetails) {
                    $manualAuthorizationDetails.open = true;
                }
            }
        };

        var saveInputs = function ($saveInput) {
            const isChecked = $saveInput.checked;

            saveInputTextboxIds.forEach(function (id) {
                if (isChecked) {
                    localStorage.setItem(id, document.getElementById(id).value);
                } else {
                    localStorage.removeItem(id);
                }
            });

            localStorage.setItem(saveInputCheckboxId, JSON.stringify(isChecked));
        };

        let $saveInput = document.getElementById(saveInputCheckboxId);

        if ($saveInput) {
            loadInputs($saveInput);

            // Save inputs when checkbox is changed
            $saveInput.addEventListener('change', function () {
                saveInputs($saveInput);
            });
        }
    }

    window.addEventListener('load', function (event) {
        saveLocal();
    });
</script>
{% endcompress %}
{% endblock js %}

{% block header %}
<div class="mx-2">
    The algorithmic timeline for Mastodon
</div>
{% endblock header %}

{% block content %}
{% unicorn 'timeline' %}
{% endblock content %}

www/templates/www/link.html
{% load humanize %}

<div class="link">
    <!-- {{ link.card.type }} -->
    <div class="header">
        <p class="title">
            <a href="{{ link.url }}">{{ link.title|truncatechars:50 }}</a>
        </p>

        {% if link.card.author_url %}
        <p>
            <a href="{{ link.card.author_url }}">{{ link.card.author_name }}</a>
        </p>
        {% endif %}
    </div>

    {% if link.card.image %}
    <div class="image">
        <img src="{{ link.card.image }}">
    </div>
    {% endif %}

    <div class="content">
        {% if link.card.description and link.card.description != link.card.title %}
        <p>
            {{ link.card.description }}
        </p>
        {% else %}
        <p>
            {{ link.most_recent_post.content|safe }}
        </p>
        {% endif %}
    </div>

    <ul class="accounts">
        {% for post in link.posts %}
        <li>
            <a href="{{ post.home_url }}" target="_blank">
                {% if post.account.avatar %}
                <span class="avatar">
                    <img src="{{ post.account.avatar }}" height="40" width="40" title="{{ post.account.acct }}">
                </span>
                {% endif %}
            </a>
        </li>
        {% endfor %}
    </ul>
</div>

www/templates/www/plus.html
{% extends 'www/base.html' %}
{% load cache compress static unicorn %}


{% block header %}
Fediview Plus ✨
{% endblock header %}

{% block js %}
{% unicorn_scripts %}
{% endblock js %}

{% block digitalocean %}
{% endblock digitalocean %}

{% block content %}
{% csrf_token %}

<p>
    👋 Hello, I'm <a href="https://indieweb.social/@adamghill/">Adam</a>. I'm a solo developer who
    believes in the promise of decentralized social media. I am looking to improve the ecosystem around
    Mastodon by creating useful tools.
</p>

<h4 class="pt-4 pb-1">Features</h4>

<ul class="mt-0">
    <li>
        Emailed daily digest with entire summary
    </li>
    <li>
        Recommended posts based on your personal post history
    </li>
    <li>
        Personal posts search engine to find one of your previous posts
    </li>
    <li>
        Get your most used tags, mentions, and emojis
    </li>
    <li>
        Get your top posts based on boosts and favorites
    </li>
    <li>
        Only include posts for a particular language
    </li>
</ul>

<h4 class="pt-4 pb-2">Video Demo</h4>

<video width="640" controls style="border: 1px solid #ccc">
    <source src="{% static 'mov/fediview-activity.mp4' %}" type="video/mp4">
</video>

<h4 class="pt-4 pb-1">Upcoming Features</h4>

<ul class="mt-0">
    <li>"If this, than that" style workflows (e.g. when a post with a certain tag is in my home timeline, automatically
        bookmark it)</li>
    <li>Store an archival of digests (in a way that is acceptable to the Mastodon ethos)</li>
    <li>Always include posts from certain accounts in the summary</li>
    <li>Schedule posts</li>
    <li>Able to boost or favorite a post directly</li>
    <li>Follow users directly</li>
    <li>See replies to a post</li>
    <li>See whether a post is part of a thread</li>
    <li>Surface posts by users who haven't posted in a while</li>
</ul>

<h4 class="pt-4 pb-1" id="sign-up">Sign Up</h4>

<ol>
    <li>
        {% if request.user.is_authenticated %}
        <strike>Login to fediview</strike>
        {% else %}
        <a href="{% url 'account:login' %}?next=/plus#sign-up">Login to fediview</a>
        {% endif %}
    </li>
    <li>
        {% if request.user.account.github_account %}
        <strike>Sponsor me on GitHub</strike>
        {% else %}
        <a href="https://github.com/sponsors/adamghill" target="_blank">Sponsor me on GitHub</a> at any level
        {% endif %}
    </li>
    <li>
        {% if request.user.account.github_account %}
        <strike>Authorize on GitHub</strike>
        {% else %}
        <a href="/plus/auth">Authorize on GitHub</a> for sponsor check
        {% endif %}
    </li>
    <li>
        {% unicorn 'sponsor' %}
    </li>
    <li>
        🎉🎉🎉
    </li>
</ol>

<div class="callout" style="margin-top: 4em;">
    If you are an open-source developer, student, or if in any way sponsoring me would cause undue financial stress,
    please <a href="https://indieweb.social/@adamghill">contact me</a> for access to Fediview Plus. ❤️
</div>
{% endblock content %}

www/templates/www/post.html
{% load humanize %}

<div class="post {% if additional_post %}additional{% endif %}">
    <div class="avatar">
        <a target="_blank" href="{{ post.account.url }}">
            <img src="{{ post.account.avatar }}">
        </a>
    </div>

    <div class="status">
        {% if post.is_recommendation %}
        <div class="recommended">
            Recommended
        </div>
        {% endif %}

        <div class="user">
            <div class="name">
                {% if post.account.display_name %}
                <a target="_blank" href="{{ post.account.url }}">
                    <span class="displayname">{{ post.account.display_name|safe }}</span>
                </a>
                <a target="_blank" href="{{ post.account.url }}">
                    <span class="username">@{{ post.account.username }}</span>
                </a>
                {% else %}
                <a target="_blank" href="{{ post.account.url }}" style="margin-top: 10px;">
                    <span class="displayname">@{{ post.account.username }}</span>
                </a>
                {% endif %}
            </div>
            <div>
                {% if not post.account.is_following %}
                <a href="https://{{ url }}/@{{ post.account.acct }}" target="_blank">
                    <button>Follow</button>
                </a>
                {% endif %}
            </div>
        </div>

        <div class="status_content">
            <div class="content">
                {{ post.content|safe }}
            </div>
            {% if post.media %}
            <div class="medias">
                {{ post.media|safe }}
            </div>
            {% endif %}
        </div>

        <div class="footer">
            <div class="date" title="{{ post.created_at|date:'DATETIME_FORMAT' }} UTC">
                <a href="{{ post.home_url }}" target="_blank">🔗&nbsp;{{ post.created_at|naturaltime }}</a>
            </div>

            <div class="reactions">
                <span title="{{ post.replies_count }} replies">⥄ {{ post.replies_count }}</span>
                <span title="{{ post.reblogs_count }} boosts" style="margin-left: 5px;">↻
                    {{ post.reblogs_count }}</span>
                <span title="{{ post.favourites_count }} favourites" style="margin-left: 5px;">★
                    {{ post.favourites_count }}</span>
            </div>
        </div>
    </div>
</div>

www/templates/www/posts.html
{% load humanize %}

{% for post in posts %}
<div class="post">
    <div class="avatar">
        <a target="_blank" href="{{ post.account_url }}">
            <img src="{{ post.account_avatar }}">
        </a>
    </div>

    <div class="status">
        <div class="user">
            {% if post.display_name %}
            <a target="_blank" href="{{ post.account_url }}">
                <span class="displayname">{{ post.display_name|safe }}</span>
            </a>
            <a target="_blank" href="{{ post.account_url }}">
                <span class="username">@{{ post.username }}</span>
            </a>
            {% else %}
            <a target="_blank" href="{{ post.account_url }}" style="margin-top: 10px;">
                <span class="displayname">@{{ post.username }}</span>
            </a>
            {% endif %}
        </div>

        <div class="status_content">
            <div class="content">
                {{ post.content|safe }}
            </div>
            {% if post.media %}
            <div class="medias">
                {{ post.media|safe }}
            </div>
            {% endif %}
        </div>

        <div class="footer">
            <div class="date" title="{{ post.created_at|date:'DATETIME_FORMAT' }} UTC">
                <a href="{{ post.home_url }}" target="_blank">🔗&nbsp;{{ post.created_at|naturaltime }}</a>
            </div>

            <div class="reactions">
                <span title="{{ post.replies_count }} replies">⥄ {{ post.replies_count }}</span>
                <span title="{{ post.reblogs_count }} boosts" style="margin-left: 5px;">↻
                    {{ post.reblogs_count }}</span>
                <span title="{{ post.favourites_count }} favourites" style="margin-left: 5px;">★
                    {{ post.favourites_count }}</span>
            </div>
        </div>
    </div>
</div>
{% endfor %}