account/urls.py
from django.urls import path

from . import views

app_name = "account"

urlpatterns = [
    path("/login", views.login, name="login"),
    path("/logout", views.logout, name="logout"),
    path("/auth", views.auth, name="auth"),
    path("/delete", views.delete, name="delete"),
    path("/unsubscribe", views.unsubscribe, name="unsubscribe"),
    path("/sample_email_digest", views.sample_email_digest, name="sample_email_digest"),
    path("", views.account, name="account"),
]

activity/urls.py
from django.urls import path

from . import views

app_name = "activity"

urlpatterns = [
    path("/search", views.search, name="search"),
    path("/delete", views.delete, name="delete"),
    path("/refresh", views.refresh, name="refresh"),
    path("", views.activity, name="activity"),
]

project/urls.py
from coltrane.sitemaps import ContentSitemap
from django.conf import settings
from django.contrib import admin
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path
from fbv.views import favicon_emoji, favicon_file

from account import urls as account_urls
from activity import urls as activity_urls
from www import urls as www_urls

ContentSitemap.protocol = "https"

sitemaps = {
    "content": ContentSitemap,
}

urlpatterns = [
    path(f"{settings.ADMIN_SITE_BASE_URL}/", admin.site.urls),
    path("unicorn/", include("django_unicorn.urls")),
    path("favicon.ico", favicon_emoji, {"emoji": "🐘"}),
    path(r"apple-touch-icon.png", favicon_emoji, {"emoji": "🐘"}),
    path(r"apple-touch-icon-precomposed.png", favicon_emoji, {"emoji": "🐘"}),
    path("robots.txt", favicon_file, {"file_path": "www/robots.txt"}),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    path("account", include(account_urls, namespace="account")),
    path("activity", include(activity_urls, namespace="activity")),
    path("", include(www_urls, namespace="www")),
    path("", include("coltrane.urls")),
]

www/urls.py
from django.urls import path

from . import views

app_name = "www"

urlpatterns = [
    path("plus/auth", views.plus_auth, name="plus_auth"),
    path("plus/oauth", views.plus_oauth, name="plus_oauth"),
    path("plus", views.plus, name="plus"),
    path("", views.index, name="index"),
]

activity/models.py
from django.db import models
from model_utils.models import TimeStampedModel
from ndarraydjango.fields import NDArrayField

from account.models import Account, Profile


class Acct(TimeStampedModel):
    """
    Named `Acct` to not conflict with Account.Account.
    """

    account = models.OneToOneField(
        Account, blank=True, null=True, related_name="acct", on_delete=models.CASCADE
    )
    acct_id = (
        models.BigIntegerField()
    )  # TODO: Convert this to text to handle non-Mastodon systems
    username = models.CharField(max_length=1024)
    url = models.URLField()
    acct = models.CharField(max_length=1024)

    @staticmethod
    def get_or_create(digest_account, current_profile: Profile):
        acct = Acct.objects.filter(acct_id=digest_account.id).first()
        known_account = None

        if current_profile.account.account_id == digest_account.id:
            known_account = current_profile.account

        if acct:
            if not acct.account and known_account:
                acct.account = known_account
                acct.save()
        else:
            acct = Acct(
                acct_id=digest_account.id,
                username=digest_account.username,
                url=digest_account.url,
                acct=digest_account.acct,
                account=known_account,
            )

            acct.save()

        return acct


class Application(TimeStampedModel):
    name = models.CharField(max_length=1024)
    website = models.CharField(blank=True, null=True, max_length=1024)


class Tag(TimeStampedModel):
    name = models.CharField(max_length=1024)


class TextEmoji(TimeStampedModel):
    text = models.CharField(max_length=1024)


class Post(TimeStampedModel):
    acct = models.ForeignKey(Acct, related_name="posts", on_delete=models.CASCADE)
    post_id = (
        models.BigIntegerField()
    )  # TODO: Convert this to text to handle non-Mastodon systems
    content = models.TextField()
    text_content = models.TextField()
    url = models.URLField()
    created_at = models.DateTimeField()
    reply_id = models.BigIntegerField(blank=True, null=True)
    is_poll = models.BooleanField(default=False)
    is_pinned = models.BooleanField(default=False)
    # public, private, etc
    visibility = models.CharField(max_length=255)
    replies_count = models.BigIntegerField(default=0)
    reblogs_count = models.BigIntegerField(default=0)
    favourites_count = models.BigIntegerField(default=0)
    edited_at = models.DateTimeField(blank=True, null=True)
    is_favourited = models.BooleanField(default=False)
    is_reblogged = models.BooleanField(default=False)
    is_muted = models.BooleanField(default=False)
    is_bookmarked = models.BooleanField(default=False)
    is_pinned = models.BooleanField(default=False)
    language = models.CharField(blank=True, null=True, max_length=32)
    tags = models.ManyToManyField(Tag)
    mentions = models.ManyToManyField(Acct)
    text_emojis = models.ManyToManyField(TextEmoji)


class PostVectors(TimeStampedModel):
    """Store a post's vectors so they do not get generated every time."""

    post_id = models.CharField(
        unique=True
    )  # This is not a ForeignKey to `Post` so that it can be stored for any post
    vectors = NDArrayField()

activity/views.py
import logging

from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.postgres.search import (
    SearchQuery,
    SearchRank,
    SearchVector,
    TrigramSimilarity,
)
from django.shortcuts import redirect, reverse
from django_q.tasks import async_task, fetch
from fbv.views import render_html

from activity.indexer import index_posts
from activity.models import Acct, Post

logger = logging.getLogger(__name__)


SEARCH_LIMIT = 100


@login_required
@render_html("activity/activity.html")
def activity(request):
    assert request.user.account.profile.has_plus, "Plus is required"

    task_id = request.GET.get("refresh")
    show_refresh_message = False

    if task_id:
        show_refresh_message = True

        task = fetch(task_id)

        if task:
            if task.success or task.stopped:
                return redirect("activity:activity")
        else:
            show_refresh_message = False

    account = request.user.account
    profile = account.profile

    posts_indexed_count = None
    replies_indexed_count = None

    acct = Acct.objects.filter(account=account).first()

    if acct:
        posts = acct.posts.all()

        posts_indexed_count = posts.count()
        replies_indexed_count = posts.filter(reply_id__isnull=False).count()

    return {
        "profile": profile,
        "posts_indexed_count": posts_indexed_count,
        "replies_indexed_count": replies_indexed_count,
        "show_refresh_message": show_refresh_message,
    }


@login_required
@render_html("activity/search.html")
def search(request):
    profile = request.user.account.profile
    assert profile.has_plus, "Plus is required"

    posts = None
    query = request.POST.get("query") or request.GET.get("q")

    if request.is_post:
        assert (
            profile.indexing_type == profile.IndexingType.CONTENT
        ), "Content indexing type is required"

        url = reverse("activity:search")
        url = f"{url}?q={query}"

        return redirect(url)

    if query:
        vector = SearchVector("text_content")
        search_query = SearchQuery(query)

        posts = (
            Post.objects.filter(acct__account__profile=profile)
            .annotate(similarity=TrigramSimilarity("text_content", query))
            .filter(similarity__gte=0.04)
            .annotate(rank=SearchRank(vector, search_query))
            .order_by("-rank", "-similarity", "-created_at")[:SEARCH_LIMIT]
        )

    # TODO: Add pagination to results

    return {"posts": posts, "query": query}


@login_required
def refresh(request):
    assert request.user.account.profile.has_plus, "Plus is required"

    task_id = async_task(index_posts, request.user.account.profile)
    logger.info(f"Refresh indexing posts with task id: {task_id}")

    messages.success(request, "Start to index posts")

    url = reverse("activity:activity")
    url = f"{url}?refresh={task_id}"

    return redirect(url)


@login_required
def delete(request):
    # Don't check for `has_plus` in the off chance that someone still has posts, but no plus anymore
    Post.objects.filter(acct__account=request.user.account).delete()

    messages.success(request, "Posts removed from index")
    return redirect("/")

activity/templates/activity/activity.html
{% extends 'www/base.html' %}
{% load cache compress humanize mastodon static unicorn %}


{% block js %}
{% unicorn_scripts %}
{% endblock js %}

{% block header %}
{{ request.user.username }}
{% endblock header %}

{% block content %}
<div style="margin-top: 3em;">
    {% if show_refresh_message %}
    <div class="callout">
        Posts are currently being indexed. Please <a href="{{ request.path_and_query }}">refresh the page</a> in a few
        minutes.
    </div>
    {% endif %}

    {% if posts_indexed_count == 0 or profile.indexing_type == profile.IndexingType.NONE %}
    <p>
        {% if profile.indexing_type == profile.IndexingType.NONE %}
        Update the <em>Post Indexing</em> option in <a href="{% url 'account:account' %}">account settings</a> to enable
        activity.
        {% else %}
        <form method="POST" action="{% url 'activity:refresh' %}">{% csrf_token %}
            <div style="text-align: right;">
                <button type="submit" style="margin-top: 1em;" class="plausible-event-name=index-posts">
                    Index Posts
                </button>
            </div>
        </form>
        {% endif %}
    </p>
    {% else %}
    <div class="center">
        <div class="box">
            <div class="title">
                {{ posts_indexed_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Posts
            </div>
        </div>

        <div class="box">
            <div class="title">
                {{ replies_indexed_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Replies
            </div>
        </div>

        <div class="box">
            <div class="title">
                {{ profile.account.favorites_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Favorites
            </div>
        </div>

        <div class="box">
            <div class="title">
                {{ profile.account.bookmarks_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Bookmarks
            </div>
        </div>

        <div class="box">
            <div class="title">
                {{ profile.account.following_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Following
            </div>
        </div>

        <div class="box">
            <div class="title">
                {{ profile.account.followers_count|default:'n/a' }}
            </div>
            <div class="subtitle">
                Followers
            </div>
        </div>
    </div>

    {% unicorn 'reports' %}

    <hr style="margin-top: 5em; border-top: 1px black dashed" />

    <div class="pt-4">
        <form method="POST" action="{% url 'activity:refresh' %}">{% csrf_token %}
            <button type="submit" class="plausible-event-name=refresh-posts">
                Re-index Posts
            </button>
            <p class="help mt-1">
                Last indexed: <span
                    title="{{ profile.last_indexed_at|default:'n/a' }}">{{ profile.last_indexed_at|naturaltime|default:'n/a' }}</span>
            </p>
        </form>
    </div>

    <details style="margin-top: 2em;">
        <summary>
            <span style="color: var(--red-600);">Remove Indexed Posts</span>
        </summary>

        <p class="help">
            Removing the indexed posts will permanently remove them from being stored by <em>Fediview</em>. Data cannot
            be recovered after it has been deleted.
            It <strong>does not</strong> delete the posts from your Mastodon instance.
        </p>

        <form method="POST" action="{% url 'activity:delete' %}">{% csrf_token %}
            <div style="text-align: right;">
                <button type="submit" style="margin-top: 1em;" class="danger plausible-event-name=delete-posts"
                    onclick="javascript: return confirm('This will remove all of the posts indexed for {{ request.user.username }}. Are you sure?');">
                    Remove Indexed Posts
                </button>
            </div>
        </form>
    </details>
</div>
{% endif %}

{% endblock content %}

activity/templates/activity/search.html
{% extends 'www/base.html' %}
{% load cache compress humanize mastodon static unicorn %}


{% block js %}
{% unicorn_scripts %}
{% endblock js %}

{% block content %}
<style>
    header {
        display: none;
    }
</style>

<div style="margin-top: 3em;">
    {% if user.account.profile.indexing_type == user.account.profile.IndexingType.CONTENT %}
    <form method="POST" action="{% url 'activity:search' %}">{% csrf_token %}
        <input name="query" value="{{ query|default:'' }}" placeholder="Text to search for..."></input>

        <div style="text-align: right;">
            <button type="submit" style="margin-top: 1em;" class="plausible-event-name=search-posts">
                Search
            </button>
        </div>
    </form>

    {% if posts %}
    {% for post in posts %}
    <div class="post">
        <div class="status">
            <div class="status_content">
                {{ post.content|safe }}
            </div>

            <div class="footer">
                <div class="reactions">
                    <a href="{{ post.url }}">Original post 🔗</a>
                </div>
            </div>
        </div>
    </div>
    {% endfor %}
    {% endif %}
    {% else %}
    Update the <em>Post Indexing</em> option to <strong>Content</strong> in <a
        href="{% url 'account:account' %}">account settings</a> to enable search.
    {% endif %}
</div>
{% endblock content %}